---
title: "Project 1"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)

```

```{r}
crime <- read_csv("data/us_crime_rates.csv")
crime

```


```{r}
crime %>%
  ggplot(aes(x=year, y=total)) + geom_line() + labs(x = "Year", y="Number of Crimes", title="Total Number of Crimes by Year") + scale_x_continuous(breaks=seq(1960,2020,4))

```

```{r}
crime1 <- data.frame(x=crime$year,
                y = c(crime$violent, crime$property),
                group = c(rep("violent", ncol(crime)),
                          rep("property", ncol(crime))))

ggplot(crime1, aes(x,y,col=group)) + geom_line() + scale_x_continuous(breaks=seq(1960,2020,4)) + scale_y_continuous(breaks=seq(0,13000000,1000000)) + labs(x="Years", y="Number of Crimes", title="Violent and Property Crimes By Year") + facet_grid(group~.)
```

```{r}
crime2 <- data.frame(x=crime$year,
                y = c(crime$murder, crime$forcible_rape, crime$robbery, crime$aggravated_assault, crime$burglary, crime$larceny_theft, crime$vehicle_theft),
                group = c(rep("murder", ncol(crime)),
                          rep("forcible_rape", ncol(crime)),
                          rep("robbery", ncol(crime)),
                          rep("aggravated_assault", ncol(crime)),
                          rep("burglary", ncol(crime)),
                          rep("larceny_theft", ncol(crime)),
                          rep("vehicle_theft", ncol(crime))))
ggplot(crime2, aes(x,y,color=group)) + geom_line() + scale_x_continuous(breaks=seq(1960,2020,4)) + labs(x="Years", y="Number of Crimes", title="Types of Crimes By Year") + facet_grid(group~.)
```
```{r}
crime3 <- crime %>%
  mutate(violent_no_agg = violent-aggravated_assault) %>%
  mutate(violent_no_mu = violent-murder) %>%
  mutate(violent_no_for = violent-forcible_rape) %>%
  mutate(violent_no_rob = violent-robbery) %>%
  mutate(prop_no_bur = property-burglary) %>%
  mutate(prop_no_lar = property-larceny_theft) %>%
  mutate(prop_no_veh = property-vehicle_theft)

crime3
```
```{r}
crime3 %>%
  ggplot(aes(x=year, y=violent_no_agg)) + geom_line() + labs(x = "Year", y="Number of Crimes", title="Violent Crimes Without Aggravated Assault by Year") + scale_x_continuous(breaks=seq(1960,2020,4))

```

```{r}
crime3 %>%
  ggplot(aes(x=year, y=violent_no_mu)) + geom_line() + labs(x = "Year", y="Total Number of Crimes", title="Violent Crimes Without Murder by Year") + scale_x_continuous(breaks=seq(1960,2020,4))
```

```{r}
crime3 %>%
  ggplot(aes(x=year, y=violent_no_for)) + geom_line() + labs(x = "Year", y="Number of Crimes", title="Violent Crimes Without Forcible Rape by Year") + scale_x_continuous(breaks=seq(1960,2020,4))
```

```{r}
crime3 %>%
  ggplot(aes(x=year, y=violent_no_rob)) + geom_line() + labs(x = "Year", y="Number of Crimes", title="Violent Crimes Without Robbery by Year") + scale_x_continuous(breaks=seq(1960,2020,4))
```

```{r}
crime3 %>%
  ggplot(aes(x=year, y=prop_no_bur)) + geom_line() + labs(x = "Year", y="Number of Crimes", title="Property Crimes Without Burgalry by Year") + scale_x_continuous(breaks=seq(1960,2020,4))
```

```{r}
crime3 %>%
  ggplot(aes(x=year, y=prop_no_lar)) + geom_line() + labs(x = "Year", y="Number of Crimes", title="Property Crimes Without Larceny Theft by Year") + scale_x_continuous(breaks=seq(1960,2020,4))
```

```{r}
crime3 %>%
  ggplot(aes(x=year, y=prop_no_veh)) + geom_line() + labs(x = "Year", y="Number of Crimes", title="Property Crimes Without Vehicle Theft by Year") + scale_x_continuous(breaks=seq(1960,2020,4))
```

