---
title: "Project 1 Report"
output: html_document
---
Ajay Iyer 


  There are many days where crimes are being committed across the world. The data set I chose was to analyze the crime rates in the USA. This data set was accessed from Openintro.org. The data starts from the year 1960 and goes till 2019. The crimes start with the total and are sorted between violent and property. The subcategories for violent crimes are murder, forcible rape, robbery and aggravated assault. The subcategories of property crimes are burglary, larceny theft, and vehicle theft. 
  The first thing I did was load the data and see what I am working with. Next, I created a graph to show the total crimes committed by the year. The first thing I noticed was that the crimes decreased after 1991. So I asked myself "What caused the crimes to decrease after 1991?" Then, I plotted the different crimes which were property and violent to see if there were any big changes to see why crimes have decreased. After plotting those, I noticed that both graphs were almost the opposite of each other; if property crime went up at a certain period, then violent crimes went down during that same period. So then I theorized the reason for the crimes to go down was one of those sub-categories and I picked burglary because I thought since technology is advancing by cameras being put everywhere, burglary would have been harder. Then, I plotted the sub-category of crimes in separate graphs so I could see what are the trends happening here. I did this so I can compare to another set of line plots which will be done at a later time. Next, I created new columns in the data set which were the type of crimes minus the sub-category of crime.   
  